services:
  reverse-proxy:
    restart: unless-stopped
    image: traefik:v2.9
    platform: linux/amd64
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  app:
    container_name: CareerDocumentsAPI
    image: ivanpedroza/career-docs-api:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SEQ_SERVER
      - SEQ_API_KEY
      - NODE_ENV
      - OPENAI_MODEL
      - OPENAI_API_KEY
      - GEMINI_API_KEY
      - GEMINI_MODEL
    labels:
      - "traefik.http.routers.app.rule=Host(`54.245.170.196`)"
      - "traefik.http.routers.app.entrypoints=web"
    depends_on:
      - seq
    networks:
      - web

  seq:
    image: datalust/seq:latest
    container_name: seqhc
    restart: unless-stopped
    volumes:
      - seqhc_data:/data
    ports:
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    labels:
      - "traefik.http.routers.seq.rule=Host(`54.245.170.196`)"
      - "traefik.http.routers.seq.entrypoints=web"
    networks:
      - web

volumes:
  seqhc_data:
  acme:

networks:
  web:
