version: "3.9"

services:
  app:
    container_name: one2one-documents_api
    # tty: true
    # stdin_open: true
    build:
      context: .
      dockerfile: app.dockerfile
      # target: build
    # image: sierasolutions/one2one-documents_api # https://stackoverflow.com/questions/33816456/how-to-tag-docker-image-with-docker-compose
    ports:
      - "3000:3000"
    environment:
      SIGNHOST_API_ENDPOINT: https://api.signhost.com/api
      SIGNHOST_TOKEN: ldX9cdPlkc.VbfW05IT4Xn3riJWFDCnTQL5ldUvhyei
      SIGNHOST_APP_KEY: eCFVjLLdheASrVyd qVmGHZi5H4W5MjEjBk2HX0gNoYHeWGIy
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    container_name: seqhc    
    restart: unless-stopped
    volumes:
      - seqhc_data:/data
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y

volumes:
  seqhc_data: